### ISSUE TITLE
IEEE: wrong template for standard type

### ISSUE THREAD

**Issue by iAnyKey** [zotero/bundled-styles#3]
# version
Zotero v.:6.0.23-beta.7+2e4fed400
after https://github.com/zotero/zotero/commit/e27c1b53358b32136e58266d807dab5346f72a3b there is a 'standard' items.

# Issue
However they are not defined in current IEEE template and output of such item:
```bibtex
@misc{ISO92831998,
  title = {Manipulating Industrial Robots - {{Performance}} Criteria and Related Test Methods},
  year = {1998},
  month = apr,
  number = {ISO 9283:1998},
  publisher = {{International Organization for Standardization}},
  address = {{Geneve, Switzerland}},
}
```
defaults to fallback definitions like that:
>[1] ‘Manipulating industrial robots - Performance criteria and related test methods’. International Organization for Standardization, Geneve, Switzerland, Apr. 1998. [Online]. Available: http://www.url.com/

which does not correspond to [IEEE Reference guide, page 15](https://ieeeauthorcenter.ieee.org/wp-content/uploads/IEEE-Reference-Guide.pdf):
![grafik](https://user-images.githubusercontent.com/57252765/229720197-39a9c408-8171-4faa-97d8-ae53227a1f5d.png)

# proposed solution
We will need few adjustments like b339485021157a8973077d271c89435f7c0d3f13 , which produce following result:
> [1] Manipulating industrial robots - Performance criteria and related test methods, ISO 9283:1998, International Organization for Standardization Geneve, Switzerland, Apr. 1998 [Online]. Available: http://www.url.com/

**Comment by dstillman** [comment]
You can submit CSL pull requests to the [CSL styles repo](https://github.com/citation-style-language/styles).
